name: Test
on: [ push, pull_request ]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          cache: 'gradle'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print info
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Build application
        run: |
          ./gradlew build -x test
      - name: Run tests
        run: |
          ./gradlew test

  build:
    name: Build on ${{ matrix.os }}
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-20.04 ]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          cache: 'gradle'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print info
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Build executable for ${{ matrix.os }}
        run: |
          ./gradlew build -x test nativeCompile
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: eOCS-Branch-Name-Generator-${{ matrix.os }}
          path: build/native/nativeCompile/*